### ISSUE TITLE
Building or Cleaning Scope for SaaS environment.

### ISSUE THREAD

**Issue by martin-charles** [cmchenr/tet-scope-builder#2]
Hello,

This is not an issue however just want to know how to use the scope builder effectively in case of SaaS environment? Since based on the code we need to set three variables via argument parser as below.

        'tet_url': {
            'descr': 'Tetration API URL (ex: https://url)',
            'env': 'SCOPE_BUILDER_TET_URL',
            'conf': 'url'
        },
        'tet_creds': {
            'descr': 'Tetration API Credentials File (ex: /User/credentials.json)',
            'env': 'SCOPE_BUILDER_TET_CREDS',
            'conf': 'creds',
                    'alt': ['tet_api_key', 'tet_api_secret']
        },
        'tenant': {
            'descr': 'Tetration Tenant Name',
            'env': 'SCOPE_BUILDER_TENANT',
            'conf': 'tenant'
        }

What would be the input for tenant, since i am trying this in SaaS environment if i give my root scope name as part of tenant , it's not working since my login itself is within a tentant..  Let me know what should be the input for tenant .

Thanks
Martin Charles A

**Comment by cmchenr** [comment]
Martin, this would be the name of your root scope.  Likely this is also the first part of your URL i.e. for "xyz.tetrationcloud.com" it would be "xyz".

**Comment by martin-charles** [comment]
Thank you... Let me try it!!

**Comment by martin-charles** [comment]
Hi, 

Hope things are good at your end!

I am just trying for clean up specific scopes, rather than a complete clean up.

I have a created a multiple child scope inside a parent , i.e. total of 52 child , but i could only able to get just one level of "child_app_scope_ids" and the removal of those child scope didn't work.  Probably due to sub-childs associated with it?

Should the script be extended to check till len (child_app_scope_ids) is zero , so that we prepare the entire scope ID list to start deleting it? 

Let me know your thoughts on this! 

<<snip>>
def clean(site_config):
    restclient = RestClient(site_config['url'],credentials_file=site_config['creds'], verify=False)
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    errors = []
    root_scope_name = site_config['tenant']

    # Gather existing scopes and IDs
    resp = restclient.get('/openapi/v1/app_scopes/')
    if resp.status_code == 200:
        current_scopes = resp.json()
        root_scope = [x for x in current_scopes if x['name'] == root_scope_name]
        app_scope_id = root_scope[0]['id']
        vrf_id = root_scope[0]['query']['value']

    print "[CHECKING] all scopes in Tetration."
    toBeDeleted = []
    toBeExamined = [app_scope_id]
    while len(toBeExamined):
        scopeId = toBeExamined.pop()
        resp = restclient.get('/openapi/v1/app_scopes/' + scopeId)
        if resp.status_code == 200:
            for scope in resp.json()["child_app_scope_ids"]:
                toBeExamined.insert(0, scope)
                toBeDeleted.append(scope)
        else:
            print "[ERROR] examining scope '{}'. This will cause problems deleting all scopes.".format(
                scopeId)
            errors.append(
                "[ERROR] examining scope '{}'. This will cause problems deleting all scopes.".format(scopeId))
            print resp, resp.text
    while len(toBeDeleted):
        scopeId = toBeDeleted.pop()
        resp = restclient.delete('/openapi/v1/app_scopes/' + scopeId)
        if resp.status_code == 200:
            print "[REMOVED] scope {} successfully.".format(scopeId)
        else:
            print "[ERROR] removing scope {}.".format(scopeId)
            errors.append("[ERROR] removing scope {}.".format(scopeId))
            print resp, resp.text

<<snip>>
